### ISSUE TITLE
INSERT INTO TABLE ERROR

### ISSUE THREAD

**Issue by HongJunDW** [dingqiangliu/vertica-plsql#1]
源SQL是：
insert into shj.test_realtime 
values(4,567,777,sysdate,'锵咚锵',sysdate);
但是实际执行的SQL是：
INSERT INTO TABLE shj.test_realtime VALUES
(4, 567, 777, 2019-03-06 01:00:42.751, '锵咚锵', 2019-03-06 01:00:42.753)
而Vertica不支持INSERT INTO后面再加上TABLE关键词，所以执行失败。

**Comment by dingqiangliu** [comment]
@HongJunDW, thanks for your issue report!
It was fixed by commit 420f7b2d4b, which  included in release [vplsql-0.0.3](/dingqiangliu/vertica-plsql/releases/tag/vplsql-0.0.3).
